version: '3'
services:
  web:
    build: .
    ports:
      - 8082:3000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
